// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FilterCom: typeof import('./../components/FilterCom.vue')['default']
    QuestionAnswerCom: typeof import('./../components/QuestionAnswerCom.vue')['default']
    QuestionCom: typeof import('./../components/QuestionCom.vue')['default']
    QuestionSetCardCom: typeof import('./../components/QuestionSetCardCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonCom: typeof import('./../components/SkeletonCom.vue')['default']
    TabBarCom: typeof import('./../components/TabBarCom.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
